### PR TITLE
Conditional prompt

### PR DESCRIPTION
**Pull request by khrizt**
Adding conditional prompt function to allow rendering Goodbye on some conditions

### CODE REVIEW

**Comment by khrizt** [comment]
Hey @xJkit, can we merge this PR? If it's all ok.

**Comment by xJkit** [comment]
Hey @khrizt:
Nice work, thanks! By the way, can you add some instructions to the readme? It might be helpful!

**Comment by khrizt** [comment]
Done! Take a look and tell me what do you think

**Comment by khrizt** [comment]
Great. Thanks!

**Comment by xJkit** [comment]
@khrizt  It would be better to provide more unit testing cases to enhance the coverage. Anyway, thank you for your contribution 💯

**Pull request merged**
